
" Emoji shortcuts
ab :smiley: 😉
ab :-) 😉
ab :sad: ☹️
ab :-( ☹️
ab :angry: 😡
ab :-\| 😡
ab :happy: 😃
ab :-D 😃
ab :love: 😍
ab :perfect: 👌
ab :check: ✔️
ab :check_green: ✅
ab :check_blue: ☑️
ab :cancel: ✖️
ab :cancel_red: ❌
ab :warning: ⚠️
ab :bulb: 💡
ab :pushpin: 📌
ab :bomb: 💣
ab :pill: 💊
ab :construction: 🚧
ab :pencil: 📝
ab :point_right: 👉
ab :thumb: 👍
ab :book: 📖
ab :link: 🔗
ab :wrench: 🔧
ab :info: ℹ️
ab :telephone: 📞
ab :email: 📧
ab :computer: 💻
ab :sandclock: ⏳
ab :stopwatch: ⏱

ab :arrow_right: →
ab :arrow_left: ←
ab :arrow_up: ↑
ab :arrow_down: ↓
ab :arrow_sides: ↔
ab :arrow_updown: ↕
ab :arrow_upleft: ↖
ab :arrow_upright: ↗
ab :arrow_downleft: ↘
ab :arrow_downright: ↙
ab :arrow_returnup: ⤴️
ab :arrow_returndown: ⤵️
ab :arrow_returnright: ↪
ab :arrow_returnleft: ↩

ab :barrow_right: ➡️
ab :barrow_left: ⬅️
ab :barrow_up: ⬆️
ab :barrow_down: ⬇️
ab :barrow_sides: ↔️
ab :barrow_updown: ↕️
ab :barrow_upleft: ↖️
ab :barrow_upright: ↗️
ab :barrow_downleft: ↘️
ab :barrow_downright: ↙️
ab :barrow_returnup: ⤴️
ab :barrow_returndown: ⤵️
ab :barrow_returnright: ↪️
ab :barrow_returnleft: ↩️



ab :lock: 🔒
ab :question: ❓
ab :magnif: 🔍
ab :rmagnif: 🔎
ab :floppy: 💾
ab :exclam: ❗
ab :exclam_white: ❕
ab :2exclam: ‼️
ab :question: ❓
ab :question_white: ❔
ab :!question: ⁉️
ab :party: 🥳
ab :broom: 🧹
ab :brush: 🖌️
ab :hammer: 🔨
ab :plaster: 🩹
ab :folder: 📂
ab :scisors: ✂️
ab :map: 🗺️
ab :eyes: 👀
ab :bug: 🪲
ab :trap: 🪤
ab :muscle: 💪
ab :power: ⚡
ab :glare: 💥
ab :sun: ☀️
ab :police: 👮
ab :lace: 🎗️
ab :dice: 🎲
ab :match: 🎯
ab :cool: 🆒
ab :sos: 🆘
ab :loud: 📢
ab :atom: ⚛️
ab :hook: 🪝
ab :anchor: ⚓
ab :lifebelt: 🛟
ab :build: 🏗️
ab :floppy: 💾
ab :makeup: 💄
ab :clock: 🕒
ab :recycle: ♻️
ab :cyclone: 🌀
ab :bell: 🔔
ab :megaphone: 📢
ab :fire: 🔥
ab :firefighter: 🚒
ab :rocket: 🚀
ab :0: 0️⃣
ab :1: 1️⃣
ab :2: 2️⃣
ab :3: 3️⃣
ab :4: 4️⃣
ab :5: 5️⃣
ab :6: 6️⃣
ab :7: 7️⃣
ab :8: 8️⃣
ab :9: 9️⃣
ab :10: 🔟
ab :#: #️⃣
ab :*: *️⃣
ab :think: 🤔
ab :detective: 🕵️
ab :monocle: 🧐


:command Smile !less<space>~/.vim/vimrc_files/emoji.vim

