
" Emoji shortcuts
ab :smiley: 😉
ab :sad: ☹️
ab :angry: 😡
ab :happy: 😃
ab :love: 😍
ab :perfect: 👌
ab :check: ✔️
ab :check_green: ✅
ab :check_blue: ☑️
ab :cancel: ✖️
ab :cancel_red: ❌
ab :warning: ⚠️
ab :bulb: 💡
ab :pushpin: 📌
ab :bomb: 💣
ab :pill: 💊
ab :construction: 🚧
ab :pencil: 📝
ab :point_right: 👉 
ab :thumb: 👍 
ab :book: 📖 
ab :link: 🔗 
ab :wrench: 🔧 
ab :info: 🛈
ab :telephone: 📞
ab :email: 📧
ab :computer: 💻
ab :sandclock: ⏳ 
ab :stopwatch: ⏱ 
ab :arrow_right: ➡️
ab :arrow_left: ⬅️
ab :arrow_up: ⬆️
ab :arrow_down: ⬇️
ab :arrow_sides: ↔️
ab :arrow_updown: ↕️
ab :arrow_upleft: ↖️
ab :arrow_upright: ↗️
ab :arrow_downleft: ↘️
ab :arrow_downright: ↙️
ab :arrow_returnup: ⤴️
ab :arrow_returndown: ⤵️
ab :arrow_returnright: ↪️
ab :arrow_returnleft: ↩️
ab :lock: 🔒
ab :question: ❓
ab :magnif: 🔍
ab :rmagnif: 🔎
ab :floppy: 💾
ab :exclam: ❗
ab :exclam_white: ❕
ab :2exclam: ‼️
ab :question: ❓ 
ab :question_white: ❔ 
ab :!question: ⁉️
ab :party: 🥳
ab :broom: 🧹
ab :brush: 🖌️
ab :hammer: 🔨
ab :plaster: 🩹

:command Smile !less<space>~/.vim/vimrc_files/emoji.vim

