#!/bin/bash

TmpDir=/tmp
[[ -n $TEMP ]] && TmpDir=$TEMP;
[[ -n $TMP ]] && TmpDir=$TMP;

ScreenHeight=20;
[[ $LINES -ge 20 ]] && ScreenHeight=$LINES;
let Margin=LINES/4

BackTitle="Sessions actives"
MenuTitle="${USER}@$(hostname)"
MenuNewSessLbl="Nova sessió"
let MenuWHeight=$ScreenHeight-5-$Margin
MenuWWidth=70
let MenuHeigth=$MenuWHeight-5

LabelEditTitle="Etiqueta per a la nova sessió"
LabelEditLabel="Etiqueta"
LabelEditWHeight=11
LabelEditWWidth=70
LabelEditHeight=3
LabelEditY1=2
LabelEditX1=5
LabelEditDefVal=""
LabelEditY2=2
LabelEditX2=15
LabelEditFlen=45
LabelEditIlen=80

#CustomOptions="--colors"
CustomOptions=""


function scrSelect {
	(echo "dialog ${CustomOptions} --backtitle \"${BackTitle}\" --menu \"${MenuTitle}:\" \
		\"${MenuWHeight}\" \"${MenuWWidth}\" \"${MenuHeigth}\" \
		$(
			# List running screen sessions.
			# Discarding '.vim_' preffixed.
			# Then extract pid and format label.
			screen -ls \
			| grep -v '\.vim_' \
			| perl -ne 's/^\s*(\d+)\.(\w.*?)\s*(\(\w+\))\s*$/\1 "\3 \2" /&&print' 2>/dev/null
		) \
		\"----\" \"${MenuNewSessLbl}\"" | bash
	) 2> "${TmpDir}/scrSelect ${PPID}.tmp"
	eval $1=$(cat "${TmpDir}/scrSelect ${PPID}.tmp")
	rm "${TmpDir}/scrSelect ${PPID}.tmp";
}


function newSession {

	# Require label for new session:
	dialog --form "${LabelEditTitle}: " "${LabelEditWHeight}" "${LabelEditWWidth}" "${LabelEditHeight}" "${LabelEditLabel}" "${LabelEditY1}" "${LabelEditX1}" "${LabelEditDefVal}" "${LabelEditY2}" "${LabelEditX2}" "${LabelEditFlen}" "${LabelEditIlen}" 2> "${TmpDir}/screensessname_${PPID}.tmp"

	# Read label from temporary file:
	MainLabel=$(cat "${TmpDir}/screensessname_${PPID}.tmp");
	rm "${TmpDir}/screensessname_${PPID}.tmp";
	
	# Clear screen and create requested session:
	clear;
	screen -S "${MainLabel}"

}


function joinSession {

	# Clear screen and attach to selected session:
	clear;
	screen -rd ${MainPID};

}



# Mandanga core:
while
	scrSelect MainPID \
	&& (
		# Check for New Session Option:
		if (
			# (New Session requested)
			test "${MainPID}" = "----"
		) then
			newSession
		else # (Normal operation)

			joinSession

		fi;
	);
do
	clear;
done;
