[ -z "$TMUX" ] && export TERM=screen-256color
set -o vi

alias less="less -R"

# lsd -ls downloads:
alias lsd="ls -lht ~/Baixades/ | head"

# Own bin dir:
export PATH="${PATH}:~/bin"

# Keep prompt short:
export PROMPT_DIRTRIM=2
