[ -z "$TMUX" ] && export TERM=screen-256color
set -o vi

alias less="less -R"

# lsd - ls downloads:
alias lsd="ls -lht ~/Baixades/ | head"

# pickd - Pick last downloaded file to current directory:
alias pickd='mv -i ~/Baixades/"$(ls -t1 ~/Baixades | head -n 1)" ./'

# some more ls aliases
alias ll='ls -1F'
alias lll='ls -lF'
alias la='ls -A'
alias l='ls -CF'

# Own bin dir:
export PATH="${PATH}:~/bin"

# Keep prompt short:
export PROMPT_DIRTRIM=2

# "open" command:
alias open='xdg-open'
