[ -z "$TMUX" ] && export TERM=screen-256color
set -o vi

alias less="less -R"

# lsd - ls downloads:
alias lsd="ls -lht ~/Baixades/ | head"

# pickd - Pick last downloaded file to current directory:
alias pickd='mv -i ~/Baixades/"$(ls -t1 ~/Baixades | head -n 1)" ./'

# some more ls aliases
alias ll='LC_ALL=C ls -1F'
alias lll='LC_ALL=C ls -lF'
alias la='LC_ALL=C ls -A'
alias l='LC_ALL=C ls -CF'

# Own bin dir:
export PATH="${PATH}:~/bin"

# Keep prompt short:
export PROMPT_DIRTRIM=2

# "open" command:
alias open='xdg-open'

# OpenAI:
export CHAT_GPT_KEY=$(cat ~/.config/openai.token);

# Legacy SSH:
alias lssh='/usr/bin/ssh -o KexAlgorithms=diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-dss'
# Credits: https://askubuntu.com/a/885396/585248

